### ISSUE TITLE
Enable `dependabot`

### ISSUE THREAD

**Issue by josecelano** [josecelano/mandelbrot-orbits-rust#5]
Add file: `.github/dependabot.yml`

```yml
version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly
```
